<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsActionType extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_action_type');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('in_use', 'boolean', null, array (  'default' => true,));
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsProcessAction as CsProcessActions', array('local' => 'id', 'foreign' => 'type_id'));
  }
  
}
