<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsAccountDivision extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_account_division');

    $this->hasColumn('account_id', 'integer', 11, array ());
    $this->hasColumn('division_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'account_id', 'foreign' => 'id'));
    $this->hasOne('CsDivision as CsDivision', array('local' => 'division_id', 'foreign' => 'id'));
  }
  
}
