<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsCalendarEventBlob extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_calendar_event_blob');

    $this->hasColumn('event_id', 'integer', 20, array ());
    $this->hasColumn('name', 'string', 250, array ());
    $this->hasColumn('blob', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsCalendarEvent as CsCalendarEvent', array('local' => 'event_id', 'foreign' => 'id'));
  }
  
}
