<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsCalendarEventReciever extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_calendar_event_reciever');

    $this->hasColumn('event_id', 'integer', 20, array ());
    $this->hasColumn('account_id', 'integer', 11, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('is_deleted', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('permission_id', 'integer', 11, array ());
    $this->hasColumn('is_erased', 'boolean', null, array ( 'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsCalendarEvent as CsCalendarEvent', array('local' => 'event_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsAccount', array('local' => 'account_id', 'foreign' => 'id'));
    $this->hasOne('CsEventStatus as CsEventStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasOne('CsObjectPermission as CsObjectPermission', array('local' => 'permission_id', 'foreign' => 'id'));
  }
  
}
