<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsCalendarEventPeriod extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_calendar_event_period');

    $this->hasColumn('event_id', 'integer', 20, array ());
    $this->hasColumn('period_id', 'integer', 11, array ());
    $this->hasColumn('condition_id', 'integer', 11, array ());
    $this->hasColumn('value', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsCalendarEvent as CsCalendarEvent', array('local' => 'event_id', 'foreign' => 'id'));
    $this->hasOne('CsEventPeriod as CsEventPeriod', array('local' => 'period_id', 'foreign' => 'id'));
    $this->hasOne('CsEventPeriodCondition as CsEventPeriodCondition', array('local' => 'condition_id', 'foreign' => 'id'));
  }
  
}
