<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsCalendarEventAlarm extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_calendar_event_alarm');

    $this->hasColumn('event_id', 'integer', 20, array ());
    $this->hasColumn('alarm_at', 'timestamp', null, array ());
    $this->hasColumn('transport_id', 'integer', 11, array ());
    $this->hasColumn('subject', 'string', 250, array ());
    $this->hasColumn('message', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsCalendarEvent as CsCalendarEvent', array('local' => 'event_id', 'foreign' => 'id'));
    $this->hasOne('CsTransport as CsTransport', array('local' => 'transport_id', 'foreign' => 'id'));
  }
  
}
