<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsCellop extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_cellop');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('gate', 'string', 150, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsAccount as CsAccounts', array('local' => 'id', 'foreign' => 'cellop_id'));
  }
  
}
