<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsChronoValue extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_chrono_value');

    $this->hasColumn('mime_type', 'string', 150, array ());
    $this->hasColumn('value', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsChronoBlob as CsChronoBlobs', array('local' => 'id', 'foreign' => 'value_id'));
    $this->hasMany('CsChronoProperty as CsChronoPropertys', array('local' => 'id', 'foreign' => 'value_id'));
  }
  
}
