<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsChronoProperty extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_chrono_property');

    $this->hasColumn('process_instance_id', 'integer', 20, array ());
    $this->hasColumn('property_instance_id', 'integer', 20, array ());
    $this->hasColumn('property_id', 'integer', 11, array ());
    $this->hasColumn('property_value_id', 'integer', 20, array ());
    $this->hasColumn('value_id', 'integer', 20, array ());
    $this->hasColumn('chrono_id', 'integer', 20, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'process_instance_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessPropertyValue as CsProcessPropertyValue', array('local' => 'property_instance_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessProperty as CsProcessProperty', array('local' => 'property_id', 'foreign' => 'id'));
    $this->hasOne('CsPropertyValue as CsPropertyValue', array('local' => 'property_value_id', 'foreign' => 'id'));
    $this->hasOne('CsChronoValue as CsChronoValue', array('local' => 'value_id', 'foreign' => 'id'));
    $this->hasOne('CsChrono as CsChrono', array('local' => 'chrono_id', 'foreign' => 'id'));
  }
  
}
