<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsChrono extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_chrono');

    $this->hasColumn('chrono_at', 'timestamp', null, array ());
    $this->hasColumn('account_id', 'integer', 11, array ());
    $this->hasColumn('from_action_id', 'integer', 20, array ());
    $this->hasColumn('to_action_id', 'integer', 20, array ());
    $this->hasColumn('instance_id', 'integer', 20, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'account_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessCurrentAction as CsFromProcessCurrentAction', array('local' => 'from_action_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessCurrentAction as CsToProcessCurrentAction', array('local' => 'to_action_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'instance_id', 'foreign' => 'id'));
    $this->hasOne('CsStatus as CsStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasMany('CsChronoProperty as CsChronoPropertys', array('local' => 'id', 'foreign' => 'chrono_id'));
  }
  
}
