<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsChronoBlob extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_chrono_blob');

    $this->hasColumn('blob_id', 'integer', 20, array ());
    $this->hasColumn('blob_value_id', 'integer', 20, array ());
    $this->hasColumn('value_id', 'integer', 20, array ());
    $this->hasColumn('blob', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsBlob as CsBlob', array('local' => 'blob_id', 'foreign' => 'id'));
    $this->hasOne('CsBlob as CsBlobValue', array('local' => 'blob_value_id', 'foreign' => 'value_id'));
    $this->hasOne('CsChronoValue as CsChronoValue', array('local' => 'value_id', 'foreign' => 'id'));
  }
  
}
