<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsContact extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_contact');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('owner_id', 'integer', 11, array ());
    $this->hasColumn('is_public', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_deleted', 'boolean', null, array (  'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'owner_id', 'foreign' => 'id'));
    $this->hasMany('CsContactList as CsContactLists', array('local' => 'id', 'foreign' => 'contact_id'));
    $this->hasMany('CsContactPermission as CsContactPermissions', array('local' => 'id', 'foreign' => 'contact_id'));
  }
  
}
