<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsContactList extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_contact_list');

    $this->hasColumn('contact_id', 'integer', 11, array ());
    $this->hasColumn('account_id', 'integer', 11, array ());
    $this->hasColumn('is_deleted', 'boolean', null, array (  'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsContact as CsContact', array('local' => 'contact_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsAccount', array('local' => 'account_id', 'foreign' => 'id'));
  }
  
}
