<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsCustomSetting extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_custom_setting');

    $this->hasColumn('account_id', 'integer', 11, array ());
    $this->hasColumn('module_id', 'integer', 11, array ());
    $this->hasColumn('setup', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'account_id', 'foreign' => 'id'));
    $this->hasOne('CsModule as CsModule', array('local' => 'module_id', 'foreign' => 'id'));
  }
  
}
