<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsDelegate extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_delegate');

    $this->hasColumn('account_id', 'integer', 11, array ());
    $this->hasColumn('delegate_id', 'integer', 11, array ());
    $this->hasColumn('started_at', 'timestamp', null, array ());
    $this->hasColumn('ended_at', 'timestamp', null, array ());
    $this->hasColumn('is_active', 'boolean', null, array (  'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'account_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsDelegateAccount', array('local' => 'delegate_id', 'foreign' => 'id'));
  }
  
}
