<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsDirectoryField extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_directory_field');

    $this->hasColumn('directory_id', 'integer', 11, array ());
    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('caption', 'string', 150, array ());
    $this->hasColumn('type_id', 'integer', 11, array ('default' => 1));
    $this->hasColumn('default_value', 'clob', null, array ());
    $this->hasColumn('autoinc', 'boolean', null, array ('default' => false));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsDirectory as CsDirectory', array('local' => 'directory_id', 'foreign' => 'id'));
    $this->hasOne('CsPropertyType as CsPropertyType', array('local' => 'type_id', 'foreign' => 'id'));
    $this->hasMany('CsDirectoryValue as CsDirectoryValues', array('local' => 'id', 'foreign' => 'field_id'));
  }
  
}
