<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsDirectoryValue extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_directory_value');

    $this->hasColumn('field_id', 'integer', 11, array ());
    $this->hasColumn('record_id', 'integer', 20, array ());
    $this->hasColumn('mime_type', 'string', 150, array ());
    $this->hasColumn('value', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsDirectoryField as CsDirectoryField', array('local' => 'field_id', 'foreign' => 'id'));
    $this->hasOne('CsDirectoryRecord as CsDirectoryRecord', array('local' => 'record_id', 'foreign' => 'id'));
    $this->hasMany('CsDirectoryBlob as CsDirectoryBlobs', array('local' => 'id', 'foreign' => 'value_id'));
  }
  
}
