<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsDirectoryRecord extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_directory_record');

    $this->hasColumn('directory_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsDirectory as CsDirectory', array('local' => 'directory_id', 'foreign' => 'id'));
    $this->hasMany('CsDirectoryValue as CsDirectoryValues', array('local' => 'id', 'foreign' => 'record_id'));
  }
  
}
