<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsEventPeriodCondition extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_event_period_condition');

    $this->hasColumn('period_id', 'integer', 11, array ());
    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsEventPeriod as CsEventPeriod', array('local' => 'period_id', 'foreign' => 'id'));
    $this->hasMany('CsCalendarEventPeriod as CsCalendarEventPeriods', array('local' => 'id', 'foreign' => 'condition_id'));
  }
  
}
