<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsMessageBlob extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_message_blob');

    $this->hasColumn('message_id', 'integer', 20, array ());
    $this->hasColumn('name', 'string', 250, array ());
    $this->hasColumn('blob', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsMessage as CsMessage', array('local' => 'message_id', 'foreign' => 'id'));
  }
  
}
