<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsMessageStatus extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_message_status');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsMessage as CsMessages', array('local' => 'id', 'foreign' => 'status_id'));
    $this->hasMany('CsMessageReciever as CsMessageRecievers', array('local' => 'id', 'foreign' => 'status_id'));
  }
  
}
