<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsMessage extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_message');

    $this->hasColumn('author_id', 'integer', 11, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('subject', 'string', 250, array ());
    $this->hasColumn('message', 'string', 4000, array ());
    $this->hasColumn('deliver_report', 'boolean', null, array ());
    $this->hasColumn('read_report', 'boolean', null, array ());
    $this->hasColumn('is_deleted', 'boolean', null, array ());
    $this->hasColumn('created_at', 'timestamp', null, array ());
    $this->hasColumn('sended_at', 'timestamp', null, array ());
    $this->hasColumn('is_erased', 'boolean', null, array ( 'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'author_id', 'foreign' => 'id'));
    $this->hasOne('CsMessageStatus as CsMessageStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasMany('CsMessageBlob as CsMessageBlobs', array('local' => 'id', 'foreign' => 'message_id'));
    $this->hasMany('CsMessageReciever as CsMessageRecievers', array('local' => 'id', 'foreign' => 'message_id'));
  }
  
}
