<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsMessageReciever extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_message_reciever');

    $this->hasColumn('message_id', 'integer', 20, array ());
    $this->hasColumn('reciever_id', 'integer', 11, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('is_deleted', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('recieved_at', 'timestamp', null, array ());
    $this->hasColumn('is_erased', 'boolean', null, array (  'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsMessage as CsMessage', array('local' => 'message_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsAccount', array('local' => 'reciever_id', 'foreign' => 'id'));
    $this->hasOne('CsMessageStatus as CsMessageStatus', array('local' => 'status_id', 'foreign' => 'id'));
  }
  
}
