<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsMime extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_mime');

    $this->hasColumn('name', 'string', 100, array ());
    $this->hasColumn('ext', 'string', 100, array ());
    $this->hasColumn('is_active', 'boolean', null, array (  'default' => true,));
  }
  

  
  public function setUp()
  {
    
  }
  
}