<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsObjectPermission extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_object_permission');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsCalendarEventReciever as CsCalendarEventRecievers', array('local' => 'id', 'foreign' => 'permission_id'));
    $this->hasMany('CsCalendarPermission as CsCalendarPermissions', array('local' => 'id', 'foreign' => 'permission_id'));
    $this->hasMany('CsContactPermission as CsContactPermissions', array('local' => 'id', 'foreign' => 'permission_id'));
    $this->hasMany('CsFilePermission as CsFilePermissions', array('local' => 'id', 'foreign' => 'permission_id'));
  }
  
}
