<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPermissionList extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_permission_list');

    $this->hasColumn('permission_id', 'integer', 11, array ());
    $this->hasColumn('module_id', 'integer', 11, array ());
    $this->hasColumn('can_read', 'boolean', null, array ());
    $this->hasColumn('can_write', 'boolean', null, array ());
    $this->hasColumn('can_delete', 'boolean', null, array ());
    $this->hasColumn('can_admin', 'boolean', null, array ());
    $this->hasColumn('can_review', 'boolean', null, array ('default' => false));
    $this->hasColumn('can_observe', 'boolean', null, array ('default' => false));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsPermission as CsPermission', array('local' => 'permission_id', 'foreign' => 'id'));
    $this->hasOne('CsModule as CsModule', array('local' => 'module_id', 'foreign' => 'id'));
  }
  
}
