<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPost extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_post');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsAccountPost as CsAccountPosts', array('local' => 'id', 'foreign' => 'post_id'));
    $this->hasMany('CsPostRelation as CsPostRelations', array('local' => 'id', 'foreign' => 'post_id'));
    $this->hasMany('CsPostRelation as CsPostRelations', array('local' => 'id', 'foreign' => 'relation_post_id'));
  }
  
}
