<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessInfoProperty extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_info_property');

    $this->hasColumn('process_id', 'integer', 11, array ());
    $this->hasColumn('property_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcess as CsProcess', array('local' => 'process_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessProperty as CsProcessProperty', array('local' => 'property_id', 'foreign' => 'id'));
  }
  
}
