<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProjectProcess extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project_process');

    $this->hasColumn('project_id', 'integer', 11, array ());
    $this->hasColumn('process_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProject as CsProject', array('local' => 'project_id', 'foreign' => 'id'));
    $this->hasOne('CsProcess as CsProcess', array('local' => 'process_id', 'foreign' => 'id'));
  }
  
}
