<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProjectInstance extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project_instance');

    $this->hasColumn('project_id', 'integer', 11, array ());
    $this->hasColumn('initiator_id', 'integer', 11, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('started_at', 'timestamp', null, array ());
    $this->hasColumn('ended_at', 'timestamp', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProject as CsProject', array('local' => 'project_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsAccount', array('local' => 'initiator_id', 'foreign' => 'id'));
    $this->hasOne('CsStatus as CsStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasMany('CsProjectProcessInstance as CsProjectProcessInstances', array('local' => 'id', 'foreign' => 'project_instance_id'));
    $this->hasMany('CsProjectPropertyValue as CsProjectPropertyValues', array('local' => 'id', 'foreign' => 'instance_id'));
  }
  
}
