<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessActionProperty extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_action_property');

    $this->hasColumn('action_id', 'integer', 11, array ());
    $this->hasColumn('property_id', 'integer', 11, array ());
    $this->hasColumn('npp', 'integer', 5, array (  'default' => 0,));
    $this->hasColumn('is_required', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_readonly', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_hidden', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_nextuser', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_childprocess', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_combo', 'boolean', null, array (  'default' => true,));
    $this->hasColumn('is_active', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('parameters', 'string', 150, array ());
    $this->hasColumn('is_multiple', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('condition', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessAction as CsProcessAction', array('local' => 'action_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessProperty as CsProcessProperty', array('local' => 'property_id', 'foreign' => 'id'));
  }
  
}
