<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessPropertyValue extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_property_value');

    $this->hasColumn('instance_id', 'integer', 20, array ());
    $this->hasColumn('property_id', 'integer', 11, array ());
    $this->hasColumn('value_id', 'integer', 20, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'instance_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessProperty as CsProcessProperty', array('local' => 'property_id', 'foreign' => 'id'));
    $this->hasOne('CsPropertyValue as CsPropertyValue', array('local' => 'value_id', 'foreign' => 'id'));
    $this->hasMany('CsChronoProperty as CsChronoPropertys', array('local' => 'id', 'foreign' => 'property_instance_id'));
  }
  
}
