<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPropertyType extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_property_type');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsProcessProperty as CsProcessPropertys', array('local' => 'id', 'foreign' => 'type_id'));
    $this->hasMany('CsProjectProperty as CsProjectPropertys', array('local' => 'id', 'foreign' => 'type_id'));
  }
  
}
