<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProjectRole extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project_role');

    $this->hasColumn('project_id', 'integer', 11, array ());
    $this->hasColumn('role_id', 'integer', 11, array ());
    $this->hasColumn('division_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProject as CsProject', array('local' => 'project_id', 'foreign' => 'id'));
    $this->hasOne('CsRole as CsRole', array('local' => 'role_id', 'foreign' => 'id'));
    $this->hasOne('CsDivision as CsDivision', array('local' => 'division_id', 'foreign' => 'id'));
  }
  
}
