<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessInstance extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_instance');

    $this->hasColumn('parent_id', 'integer', 20, array ());
    $this->hasColumn('process_id', 'integer', 11, array ());
    $this->hasColumn('initiator_id', 'integer', 11, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('started_at', 'timestamp', null, array ());
    $this->hasColumn('ended_at', 'timestamp', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'parent_id', 'foreign' => 'id'));
    $this->hasOne('CsProcess as CsProcess', array('local' => 'process_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsAccount', array('local' => 'initiator_id', 'foreign' => 'id'));
    $this->hasOne('CsStatus as CsStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasMany('CsAccountToday as CsAccountTodays', array('local' => 'id', 'foreign' => 'process_instance_id'));
    $this->hasMany('CsChrono as CsChronos', array('local' => 'id', 'foreign' => 'instance_id'));
    $this->hasMany('CsChronoAction as CsChronoActions', array('local' => 'id', 'foreign' => 'process_instance_id'));
    $this->hasMany('CsChronoProperty as CsChronoPropertys', array('local' => 'id', 'foreign' => 'process_instance_id'));
    $this->hasMany('CsProcessActionChild as CsProcessActionChilds', array('local' => 'id', 'foreign' => 'process_id'));
    $this->hasMany('CsProcessCurrentAction as CsProcessCurrentActions', array('local' => 'id', 'foreign' => 'instance_id'));
    $this->hasMany('CsProcessInstance as CsProcessInstances', array('local' => 'id', 'foreign' => 'parent_id'));
    $this->hasMany('CsProcessPropertyValue as CsProcessPropertyValues', array('local' => 'id', 'foreign' => 'instance_id'));
    $this->hasMany('CsProjectProcessInstance as CsProjectProcessInstances', array('local' => 'id', 'foreign' => 'process_instance_id'));
  }
  
}
