<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProjectPropertyValue extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project_property_value');

    $this->hasColumn('instance_id', 'integer', 20, array ());
    $this->hasColumn('property_id', 'integer', 11, array ());
    $this->hasColumn('value_id', 'integer', 20, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProjectInstance as CsProjectInstance', array('local' => 'instance_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessProperty as CsProcessProperty', array('local' => 'property_id', 'foreign' => 'id'));
    $this->hasOne('CsPropertyValue as CsPropertyValue', array('local' => 'value_id', 'foreign' => 'id'));
  }
  
}
