<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessCurrentAction extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_current_action');

    $this->hasColumn('instance_id', 'integer', 20, array ());
    $this->hasColumn('action_id', 'integer', 11, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('initiator_id', 'integer', 11, array ());
    $this->hasColumn('performer_id', 'integer', 11, array ());
    $this->hasColumn('planed', 'string', 4000, array ());
    $this->hasColumn('fixed_planed', 'boolean', null, array (  'default' => true,));
    $this->hasColumn('started_at', 'timestamp', null, array ());
    $this->hasColumn('ended_at', 'timestamp', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'instance_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessAction as CsProcessAction', array('local' => 'action_id', 'foreign' => 'id'));
    $this->hasOne('CsStatus as CsStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsInitiatorAccount', array('local' => 'initiator_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsPerformerAccount', array('local' => 'performer_id', 'foreign' => 'id'));
    $this->hasMany('CsAccountToday as CsAccountTodays', array('local' => 'id', 'foreign' => 'action_instance_id'));
    $this->hasMany('CsChrono as CsChronosFrom', array('local' => 'id', 'foreign' => 'from_action_id'));
    $this->hasMany('CsChrono as CsChronosTo', array('local' => 'id', 'foreign' => 'to_action_id'));
    $this->hasMany('CsChronoAction as CsChronoActions', array('local' => 'id', 'foreign' => 'action_instance_id'));
    $this->hasMany('CsProcessActionChild as CsProcessActionChilds', array('local' => 'id', 'foreign' => 'action_id'));
    $this->hasMany('CsProcessCurrentActionPerformer as CsProcessCurrentActionPerformers', array('local' => 'id', 'foreign' => 'instance_action_id'));
  }
  
}
