<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessActionTransport extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_action_transport');

    $this->hasColumn('action_id', 'integer', 11, array ());
    $this->hasColumn('transport_id', 'integer', 11, array ());
    $this->hasColumn('subject_template', 'string', 4000, array ());
    $this->hasColumn('text_template', 'string', 4000, array ());
    $this->hasColumn('recipients_template', 'string', 4000, array ());
    $this->hasColumn('event_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessAction as CsProcessAction', array('local' => 'action_id', 'foreign' => 'id'));
    $this->hasOne('CsTransport as CsTransport', array('local' => 'transport_id', 'foreign' => 'id'));
    $this->hasOne('CsEvent as CsEvent', array('local' => 'event_id', 'foreign' => 'id'));
  }
  
}
