<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessAction extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_action');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('process_id', 'integer', 11, array ());
    $this->hasColumn('role_id', 'integer', 11, array ());
    $this->hasColumn('type_id', 'integer', 11, array ());
    $this->hasColumn('is_interactive', 'boolean', null, array ());
    $this->hasColumn('weight', 'float', 10, array (  'default' => 0,));
    $this->hasColumn('planed', 'string', 4000, array ());
    $this->hasColumn('fixed_planed', 'boolean', null, array (  'default' => true,));
    $this->hasColumn('form', 'clob', null, array ());
    $this->hasColumn('code', 'clob', null, array ());
    $this->hasColumn('npp', 'integer', 5, array ());
    $this->hasColumn('true_action_id', 'integer', 11, array ());
    $this->hasColumn('false_action_id', 'integer', 11, array ());
    $this->hasColumn('condition', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcess as CsProcess', array('local' => 'process_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessRole as CsProcessRole', array('local' => 'role_id', 'foreign' => 'id'));
    $this->hasOne('CsActionType as CsActionType', array('local' => 'type_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessAction as CsProcessTrueAction', array('local' => 'true_action_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessAction as CsProcessFalseAction', array('local' => 'false_action_id', 'foreign' => 'id'));
    $this->hasMany('CsProcessAction as CsProcessTrueActions', array('local' => 'id', 'foreign' => 'true_action_id'));
    $this->hasMany('CsProcessAction as CsProcessFalseActions', array('local' => 'id', 'foreign' => 'false_action_id'));
    $this->hasMany('CsProcessActionProperty as CsProcessActionPropertys', array('local' => 'id', 'foreign' => 'action_id'));
    $this->hasMany('CsProcessActionTransport as CsProcessActionTransports', array('local' => 'id', 'foreign' => 'action_id'));
    $this->hasMany('CsProcessCurrentAction as CsProcessCurrentActions', array('local' => 'id', 'foreign' => 'action_id'));
    $this->hasMany('CsProcessTransition as CsProcessFromTransitions', array('local' => 'id', 'foreign' => 'from_action_id'));
    $this->hasMany('CsProcessTransition as CsProcessToTransitions', array('local' => 'id', 'foreign' => 'to_action_id'));
  }
  
}
