<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessActionChild extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_action_child');

    $this->hasColumn('action_id', 'integer', 20, array ());
    $this->hasColumn('process_id', 'integer', 20, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessCurrentAction as CsProcessCurrentAction', array('local' => 'action_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'process_id', 'foreign' => 'id'));
  }
  
}
