<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessTransition extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_transition');

    $this->hasColumn('process_id', 'integer', 11, array ());
    $this->hasColumn('from_action_id', 'integer', 11, array ());
    $this->hasColumn('to_action_id', 'integer', 11, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcess as CsProcess', array('local' => 'process_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessAction as CsProcessFromAction', array('local' => 'from_action_id', 'foreign' => 'id'));
    $this->hasOne('CsProcessAction as CsProcessToAction', array('local' => 'to_action_id', 'foreign' => 'id'));
  }
  
}
