<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessProperty extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_property');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('process_id', 'integer', 11, array ());
    $this->hasColumn('sign_id', 'integer', 11, array (  'default' => 1,));
    $this->hasColumn('type_id', 'integer', 11, array (  'default' => 1,));
    $this->hasColumn('default_value', 'string', 4000, array ());
    $this->hasColumn('is_list', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('is_name_as_value', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('directory_id', 'integer', 11, array ());
    $this->hasColumn('value_field', 'string', 4000, array (  'default' => 'name',));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcess as CsProcess', array('local' => 'process_id', 'foreign' => 'id'));
    $this->hasOne('CsSign as CsSign', array('local' => 'sign_id', 'foreign' => 'id'));
    $this->hasOne('CsPropertyType as CsPropertyType', array('local' => 'type_id', 'foreign' => 'id'));
    $this->hasOne('CsDirectory as CsDirectory', array('local' => 'directory_id', 'foreign' => 'id'));
    $this->hasMany('CsProcessActionProperty as CsProcessActionPropertys', array('local' => 'id', 'foreign' => 'property_id'));
    $this->hasMany('CsProcessInfoProperty as CsProcessInfoPropertys', array('local' => 'id', 'foreign' => 'property_id'));
    $this->hasMany('CsProcessPropertyValue as CsProcessPropertyValues', array('local' => 'id', 'foreign' => 'property_id'));
    $this->hasMany('CsProjectPropertyValue as CsProjectPropertyValues', array('local' => 'id', 'foreign' => 'property_id'));
  }
  
}
