<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProcessCurrentActionPerformer extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_process_current_action_performer');

    $this->hasColumn('instance_action_id', 'integer', 20, array ());
    $this->hasColumn('status_id', 'integer', 11, array ());
    $this->hasColumn('initiator_id', 'integer', 11, array ());
    $this->hasColumn('performer_id', 'integer', 11, array ());
    $this->hasColumn('started_at', 'timestamp', null, array ());
    $this->hasColumn('ended_at', 'timestamp', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessCurrentAction as CsProcessCurrentAction', array('local' => 'instance_action_id', 'foreign' => 'id'));
    $this->hasOne('CsStatus as CsStatus', array('local' => 'status_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsInitiatorAccount', array('local' => 'initiator_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsPerformerAccount', array('local' => 'performer_id', 'foreign' => 'id'));
  }
  
}
