<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProjectProperty extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project_property');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('project_id', 'integer', 11, array ());
    $this->hasColumn('sign_id', 'integer', 11, array (  'default' => 1,));
    $this->hasColumn('type_id', 'integer', 11, array (  'default' => 1,));
    $this->hasColumn('default_value', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProject as CsProject', array('local' => 'project_id', 'foreign' => 'id'));
    $this->hasOne('CsSign as CsSign', array('local' => 'sign_id', 'foreign' => 'id'));
    $this->hasOne('CsPropertyType as CsPropertyType', array('local' => 'type_id', 'foreign' => 'id'));
  }
  
}
