<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPropertyValue extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_property_value');

    $this->hasColumn('mime_type', 'string', 150, array ());
    $this->hasColumn('value', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsBlob as CsBlobs', array('local' => 'id', 'foreign' => 'value_id'));
    $this->hasMany('CsProcessPropertyValue as CsProcessPropertyValues', array('local' => 'id', 'foreign' => 'value_id'));
    $this->hasMany('CsProjectPropertyValue as CsProjectPropertyValues', array('local' => 'id', 'foreign' => 'value_id'));
  }
  
}
