<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProject extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('is_permanent', 'boolean', null, array ());
    $this->hasColumn('author_id', 'integer', 11, array ());
    $this->hasColumn('version', 'float', 10, array (  'default' => 1,));
    $this->hasColumn('created_at', 'timestamp', null, array ());
    $this->hasColumn('activated_at', 'timestamp', null, array ());
    $this->hasColumn('is_active', 'boolean', null, array ());
    $this->hasColumn('is_system', 'boolean', null, array (  'default' => false,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsAccount as CsAccount', array('local' => 'author_id', 'foreign' => 'id'));
    $this->hasMany('CsProjectInstance as CsProjectInstances', array('local' => 'id', 'foreign' => 'project_id'));
    $this->hasMany('CsProjectProcess as CsProjectProcesss', array('local' => 'id', 'foreign' => 'project_id'));
    $this->hasMany('CsProjectProperty as CsProjectPropertys', array('local' => 'id', 'foreign' => 'project_id'));
    $this->hasMany('CsProjectRole as CsProjectRoles', array('local' => 'id', 'foreign' => 'project_id'));
  }
  
}
