<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsProjectProcessInstance extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_project_process_instance');

    $this->hasColumn('process_instance_id', 'integer', 20, array ());
    $this->hasColumn('project_instance_id', 'integer', 20, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsProcessInstance as CsProcessInstance', array('local' => 'process_instance_id', 'foreign' => 'id'));
    $this->hasOne('CsProjectInstance as CsProjectInstance', array('local' => 'project_instance_id', 'foreign' => 'id'));
  }
  
}
