<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPublicBlob extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_public_blob');

    $this->hasColumn('file_id', 'integer', 20, array ());
    $this->hasColumn('blob', 'clob', null, array ());
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsPublicFile as CsPublicFile', array('local' => 'file_id', 'foreign' => 'id'));
  }
  
}
