<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPublicDocument extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_public_document');

    $this->hasColumn('parent_id', 'integer', 20, array ());
    $this->hasColumn('topic_id', 'integer', 11, array ());
    $this->hasColumn('name', 'string', 250, array ());
    $this->hasColumn('description', 'clob', null, array ());
    $this->hasColumn('created_at', 'timestamp', null, array (  'default' => 'now()',));
    $this->hasColumn('updated_at', 'timestamp', null, array (  'default' => 'now()',));
    $this->hasColumn('created_by', 'integer', 11, array ());
    $this->hasColumn('updated_by', 'integer', 11, array ());
    $this->hasColumn('is_active', 'boolean', null, array (  'default' => false,));
    $this->hasColumn('npp', 'integer', 11, array (  'default' => 0,));
  }
  

  
  public function setUp()
  {
    $this->hasOne('CsPublicDocument as CsPublicDocument', array('local' => 'parent_id', 'foreign' => 'id'));
    $this->hasOne('CsPublicTopic as CsPublicTopic', array('local' => 'topic_id', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsCreatorAccount', array('local' => 'created_by', 'foreign' => 'id'));
    $this->hasOne('CsAccount as CsUpdaterAccount', array('local' => 'updated_by', 'foreign' => 'id'));
    $this->hasMany('CsPublicDocument as CsPublicDocuments', array('local' => 'id', 'foreign' => 'parent_id'));
  }
  
}
