<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsPublicFile extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_public_file');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('filename', 'string', 250, array ());
    $this->hasColumn('mime_type', 'string', 100, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsPublicBlob as CsPublicBlobs', array('local' => 'id', 'foreign' => 'file_id'));
  }
  
}
