<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsRole extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_role');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsProcessRole as CsProcessRoles', array('local' => 'id', 'foreign' => 'role_id'));
    $this->hasMany('CsProjectRole as CsProjectRoles', array('local' => 'id', 'foreign' => 'role_id'));
  }
  
}
