<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsSign extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_sign');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsProcessProperty as CsProcessPropertys', array('local' => 'id', 'foreign' => 'sign_id'));
    $this->hasMany('CsProjectProperty as CsProjectPropertys', array('local' => 'id', 'foreign' => 'sign_id'));
  }
  
}
