<?php
/*
 * Base class; DO NOT EDIT
 *
 * auto-generated by the sfDoctrine plugin
 */
class CsTransport extends Doctrine_Record
{
  
  
  public function setTableDefinition()
  {
    $this->setTableName('cs_transport');

    $this->hasColumn('name', 'string', 150, array ());
    $this->hasColumn('description', 'string', 4000, array ());
    $this->hasColumn('server_address', 'string', 50, array ());
    $this->hasColumn('server_login', 'string', 30, array ());
    $this->hasColumn('server_passwd', 'string', 30, array ());
    $this->hasColumn('server_port', 'string', 10, array ());
    $this->hasColumn('class_name', 'string', 30, array ());
  }
  

  
  public function setUp()
  {
    $this->hasMany('CsCalendarEventAlarm as CsCalendarEventAlarms', array('local' => 'id', 'foreign' => 'transport_id'));
    $this->hasMany('CsProcessActionTransport as CsProcessActionTransports', array('local' => 'id', 'foreign' => 'transport_id'));
    $this->hasMany('CsProcessTransport as CsProcessTransports', array('local' => 'id', 'foreign' => 'transport_id'));
  }
  
}
