<?php

// $Id$

class Constants {
	const ACTIVE		= 1;
	const NOT_ACTIVE	= 0;

	const TRUE			= 1;
	const FALSE			= 0;

	const PROCESS_STATUS_NONE				= NULL;
	const PROCESS_STATUS_IN_PROGRESS		= 1;
	const PROCESS_STATUS_TERMINATED			= 2;
	const PROCESS_STATUS_WAITING			= 3;
	const PROCESS_STATUS_COMPLETED			= 4;
	const PROCESS_STATUS_ERROR				= 5;
	const PROCESS_STATUS_DELETED			= 6;
	const PROCESS_STATUS_SKIPED				= 7;
	const PROCESS_STATUS_CHILD_IN_PROGRESS	= 8;
	const PROCESS_STATUS_CHILD_TERMINATED	= 9;
	const PROCESS_STATUS_CHILD_WAITING		= 10;
	const PROCESS_STATUS_CHILD_COMPLETED	= 11;
	const PROCESS_STATUS_CHILD_ERROR		= 12;
	const PROCESS_STATUS_CHILD_DELETED		= 13;
	const PROCESS_STATUS_CHILD_SKIPED		= 14;

	const PROJECT_STATUS_NONE			= Constants::PROCESS_STATUS_NONE;
	const PROJECT_STATUS_IN_PROGRESS	= Constants::PROCESS_STATUS_IN_PROGRESS;
	const PROJECT_STATUS_TERMINATED		= Constants::PROCESS_STATUS_TERMINATED;
	const PROJECT_STATUS_WAITING		= Constants::PROCESS_STATUS_WAITING;
	const PROJECT_STATUS_COMPLETED		= Constants::PROCESS_STATUS_COMPLETED;
	const PROJECT_STATUS_ERROR			= Constants::PROCESS_STATUS_ERROR;
	const PROJECT_STATUS_DELETED		= Constants::PROCESS_STATUS_DELETED;
	const PROJECT_STATUS_SKIPED			= Constants::PROCESS_STATUS_SKIPED;

	const ACTION_STATUS_NONE			= Constants::PROCESS_STATUS_NONE;
	const ACTION_STATUS_IN_PROGRESS		= Constants::PROCESS_STATUS_IN_PROGRESS;
	const ACTION_STATUS_TERMINATED		= Constants::PROCESS_STATUS_TERMINATED;
	const ACTION_STATUS_WAITING			= Constants::PROCESS_STATUS_WAITING;
	const ACTION_STATUS_COMPLETED		= Constants::PROCESS_STATUS_COMPLETED;
	const ACTION_STATUS_ERROR			= Constants::PROCESS_STATUS_ERROR;
	const ACTION_STATUS_DELETED			= Constants::PROCESS_STATUS_DELETED;
	const ACTION_STATUS_SKIPED			= Constants::PROCESS_STATUS_SKIPED;

	const ACTION_TYPE_NONE				= NULL;
	const ACTION_TYPE_START				= 1;
	const ACTION_TYPE_ACTION			= 2;
	const ACTION_TYPE_SWITCH			= 3;
	const ACTION_TYPE_SPLIT				= 4;
	const ACTION_TYPE_JOIN				= 5;
	const ACTION_TYPE_END				= 6;
	const ACTION_TYPE_STANDALONE		= 7;
	const ACTION_TYPE_INFO				= 8;

	const PROPERTY_SIGN_NONE			= NULL;
	const PROPERTY_SIGN_READWRITE		= 1;
	const PROPERTY_SIGN_READONLY		= 2;
	const PROPERTY_SIGN_HIDDEN			= 3;

	const PROPERTY_TYPE_NONE			= NULL;
	const PROPERTY_TYPE_TEXT			= 1;
	const PROPERTY_TYPE_STRING			= 2;
	const PROPERTY_TYPE_NUMBER			= 3;
	const PROPERTY_TYPE_DATE			= 4;
	const PROPERTY_TYPE_TIME			= 5;
	const PROPERTY_TYPE_DATETIME		= 6;
	const PROPERTY_TYPE_BOOL			= 7;
	const PROPERTY_TYPE_OBJECT			= 8;

	const EVENT_BEFORE_PROCESS_START	= 1;
	const EVENT_AFTER_PROCESS_END		= 2;
	const EVENT_BEFORE_ANY_ACTION_START	= 3;
	const EVENT_AFTER_ANY_ACTION_END	= 4;
	const EVENT_AFTER_ANY_ACTION_START	= 5;
	const EVENT_BEFORE_ANY_ACTION_END	= 6;
	const EVENT_AFTER_PROCESS_START		= 7;
	const EVENT_BEFORE_PROCESS_END		= 8;
	const EVENT_BEFORE_INT_ACTION_START	= 9;
	const EVENT_AFTER_INT_ACTION_START	= 10;
	const EVENT_BEFORE_INT_ACTION_END	= 11;
	const EVENT_AFTER_INT_ACTION_END	= 12;
	const EVENT_BEFORE_NOT_ACTION_START	= 13;
	const EVENT_AFTER_NOT_ACTION_START	= 14;
	const EVENT_BEFORE_NOT_ACTION_END	= 15;
	const EVENT_AFTER_NOT_ACTION_END	= 16;

	const PERMISSION_NONE				= NULL;
	const PERMISSION_NO_ACCESS			= 1;
	const PERMISSION_READ_ONLY			= 2;
	const PERMISSION_READ_WRITE			= 3;
	const PERMISSION_READ_WRITE_DELETE	= 4;
	const PERMISSION_FULL_ACCESS		= 5;

	const MESSAGE_NONE					= NULL;
	const MESSAGE_CREATED				= 1;
	const MESSAGE_SENDED				= 2;
	const MESSAGE_RECIEVED				= 3;
	const MESSAGE_READED				= 4;
	const MESSAGE_RESENDED				= 5;
	const MESSAGE_RERECIEVED			= 6;
	const MESSAGE_DELETED				= 7;

	const EVENT_PRIORITY_NONE			= NULL;
	const EVENT_PRIORITY_LOW			= 1;
	const EVENT_PRIORITY_NORMAL			= 2;
	const EVENT_PRIORITY_MIDDLE			= 3;
	const EVENT_PRIORITY_HIGH			= 4;
	const EVENT_PRIORITY_VERY_HIGH		= 5;
	const EVENT_PRIORITY_HIGHEST		= 6;

	const EVENT_STATUS_NONE				= NULL;
	const EVENT_STATUS_CREATED			= 1;
	const EVENT_STATUS_WAITING			= 2;
	const EVENT_STATUS_IN_PROGRESS		= 3;
	const EVENT_STATUS_COMPLETED		= 4;
	const EVENT_STATUS_CANCELED			= 5;
	const EVENT_STATUS_DELETED			= 6;

	const EVENT_PERIOD_NONE				= NULL;
	const EVENT_PERIOD_DAILY			= 1;
	const EVENT_PERIOD_WEEKLY			= 2;
	const EVENT_PERIOD_MOUNTHLY			= 3;
	const EVENT_PERIOD_YEARLY			= 4;

	const EVENT_PERIOD_DAILY_EVERY_DAY			= 1;
	const EVENT_PERIOD_DAILY_EVERY_WORKDAY		= 2;
	const EVENT_PERIOD_WEEKLY_EVERY_DAY			= 3;
	const EVENT_PERIOD_MOUNTHLY_EVERY_DAY		= 4;
	const EVENT_PERIOD_MOUNTHLY_EVERY_WEEKDAY	= 5;
	const EVENT_PERIOD_YEARLY_EVERY_DAY			= 6;
	const EVENT_PERIOD_YEARLY_EVERY_MONTH_DAY	= 7;
	const EVENT_PERIOD_YEARLY_EVERY_WEEKDAY		= 8;

}
?>